#!/usr/bin/php -q
<?php 
require_once ('vendor/autoload.php');
if (file_exists( 'vendor/thanhtaivtt/taiscript/src/taiscript/bootstrap.php' ) ) {
	require_once ('vendor/thanhtaivtt/taiscript/src/taiscript/bootstrap.php');
} else {
	echo 'Missing vendor, you need run: conposer install';
}
?>